### ISSUE TITLE
D3D8on12 support

### ISSUE THREAD

**Issue by donizettilorenzo** [narzoul/ForceD3D9On12#2]
Can you do the same for D3D8on12 (a way to force it)?

EDIT: oh, it's ALREADY present in the x86 package, thanks!

Maybe rename the project to "Force D3DXon12" ?

**Comment by narzoul** [comment]
The component it uses is called [D3D9On12](https://github.com/microsoft/D3D9On12), it would be misleading to name this one differently. D3D9On12 replaces the WDDM user-mode display driver, not the individual runtimes. All DX runtime versions up to 9 use the same WDDM display driver. There are no separate drivers for Direct3D 8 or DirectDraw under WDDM, like there was with XPDM drivers. It was all merged into one.

**Comment by ThreeDeeJay** [comment]
@narzoul So should I add more API versions for D3D9On12 in https://www.pcgamingwiki.com/wiki/Glossary:Display_wrapper#Direct3D_wrappers?
If so, which? And btw how well do <=D3D8 games work in general?👀

**Comment by TheSilkMan** [comment]
What is the main benefits for using this D3D9on12? For instance, can it cause graphics in older games to look better by converting them into dx12 equivalents? The obvious benefit is that we csn run older games on DX12 machines.

**Comment by narzoul** [comment]
> @narzoul So should I add more API versions for D3D9On12 in https://www.pcgamingwiki.com/wiki/Glossary:Display_wrapper#Direct3D_wrappers?
If so, which?

As I wrote before, everything up to DX9 can use D3D9On12. Even DirectDraw. So it should be Direct3D 2-9 and DirectDraw 1-7.

> And btw how well do <=D3D8 games work in general?👀

I don't know, I haven't tested it much, especially recently.

> What is the main benefits for using this D3D9on12?

Compatibility, possibly. Maybe performance, but last I tested it I think it was worse than native in general. But this also depends on how bad the native drivers are...

> For instance, can it cause graphics in older games to look better by converting them into dx12 equivalents?

No, unless you consider using it with something like Reshade, which might not work otherwise. But I haven't tried that.
